INSERT INTO club (id, name, country, sport, description, foundation_year) VALUES (1, 'Bayern Monachium', 'Niemcy', 'FOOTBALL', 'Niemiecki klub sportowy z siedzibą w Monachium przy Strasees Bahn w Bawarii. Jest to najbardziej znany i najbardziej utytułowany niemiecki klub, a także jeden z najbardziej utytułowanych klubów na świecie. 29 razy zdobył tytuł Mistrza Niemiec, 19 razy wygrał Puchar Niemiec. Ponadto w rozgrywkach europejskich dwukrotnie triumfował w Lidze Mistrzów i trzykrotnie (przed jej utworzeniem) w Pucharze Europy Mistrzów Klubowych oraz po jednym razie wygrał Puchar Zdobywców Pucharów, Puchar UEFA oraz Superpuchar Europy co czyni go jednym z nielicznych klubów, który triumfował we wszystkich możliwych turniejach rozgrywanych w Europie.', 1900);
INSERT INTO club (id, name, country, sport, description, foundation_year) VALUES (2, 'Manchester City', 'Anglia', 'FOOTBALL', 'Angielski klub piłkarski z siedzibą w Manchesterze. Obecnie występuje w Premier League. Klub powstał w 1880 roku jako Saint Marks (West Gorton), w 1887 został przemianowany na Ardwick AFC, a obecną nazwę nosi od 1894. Zdobył sześć tytułów Mistrza Anglii, sześć razy wygrał Puchar Anglii, sześć razy – Puchar Ligi Angielskiej, a raz – Puchar Zdobywców Pucharów. Największe sukcesy osiągnął w latach 60. i 70. XX wieku, pod kierunkiem trenerów Joe Mercera i Malcolma Allisona mających do dyspozycji między innymi takich piłkarzy jak Colin Bell i Francis Lee.', 1880);
INSERT INTO club (id, name, country, sport, description, foundation_year) VALUES (3, 'Real Madryt', 'Hiszpania', 'FOOTBALL', ' Hiszpański klub sportowy powstały w 1902 roku. Słynie głównie z sukcesów istniejącej od chwili założenia drużyny piłki nożnej, która 33 razy zdobyła mistrzostwo Hiszpanii, 13 razy Puchar Europy/Ligę Mistrzów, a także wiele innych trofeów, w tym przyznany w 2000 roku przez FIFA tytuł najlepszego klubu w XX wieku. Od 1947 roku drużyna ta rozgrywa domowe spotkania na stadionie Santiago Bernabéu, nazwanym na cześć byłego prezesa, za którego czasów klub zdobył najwięcej trofeów', 1902);
INSERT INTO club (id, name, country, sport, description, foundation_year) VALUES (4, 'SSC Napoli', 'Włochy', 'FOOTBALL', 'Włoski klub piłkarski z siedzibą w Neapolu, po sześciu latach przerwy powrócił do rozgrywek Serie A w sezonie 2007/2008. Napoli, pomimo problemów finansowych i trwającego od wielu lat kryzysu, znajduje się wśród klubów z największą liczbą fanów we Włoszech, związane jest to także z legendą klubu Diego Maradoną, uważanym za jednego z najlepszych piłkarzy w historii. SSC Napoli zostało założone w sierpniu 2004 pod nazwą Napoli Soccer przez Aurelio de Laurentiisa, znanego producenta filmowego, po bankructwie klubu SSC Napoli.', 1926);
INSERT INTO club (id, name, country, sport, description, foundation_year) VALUES (5, 'Paris Saint-Germain', 'Francja', 'FOOTBALL', 'Francuski klub piłkarski z siedzibą w Paryżu, rozgrywający mecze na stadionie Parc des Princes. Założony został w 1970 i aktualnie występuje w rozgrywkach Ligue 1. Drużyna należy do najbardziej utytułowanych w swoim kraju, mając na koncie m.in. osiem mistrzostw Francji, dwanaście Pucharów Francji, siedem[1] Superpucharów Francji, osiem Pucharów Ligi Francuskiej oraz Puchar Zdobywców Pucharów i Puchar Intertoto.', 1970);
INSERT INTO club (id, name, country, sport, description, foundation_year) VALUES (6, 'Śląsk Wrocław', 'Polska', 'FOOTBALL', 'Polski klub piłkarski z siedzibą we Wrocławiu, występujący w Ekstraklasie. Dwukrotny mistrz Polski (1977, 2012), trzykrotny wicemistrz Polski (1978, 1982, 2011), dwukrotny zdobywca Pucharu Polski (1976, 1987), dwukrotny zdobywca Superpucharu Polski (1987, 2012) oraz zdobywca Pucharu Ekstraklasy (2009).', 1947);

INSERT INTO footballer (first_name, last_name, age, country, club_id) VALUES ('Manuel', 'Neuer', 34, 'NIEMCY', 1);
INSERT INTO footballer (first_name, last_name, age, country, club_id) VALUES ('Robert', 'Lewandowski', 32, 'POLSKA', 1);
INSERT INTO footballer (first_name, last_name, age, country, club_id) VALUES ('Kevin', 'De Bruyne', 29, 'BELGIA', 2);
INSERT INTO footballer (first_name, last_name, age, country, club_id) VALUES ('Sergio', 'Agüero', 32, 'ARGENTYNA', 2);
INSERT INTO footballer (first_name, last_name, age, country, club_id) VALUES ('Luka', 'Modrić', 35, 'CHORWACJA', 3);
INSERT INTO footballer (first_name, last_name, age, country, club_id) VALUES ('Sergio', 'Ramos', 34, 'HISZPANIA', 3);
INSERT INTO footballer (first_name, last_name, age, country, club_id) VALUES ('Arkadiusz', 'Milik', 26, 'POLSKA', 4);
INSERT INTO footballer (first_name, last_name, age, country, club_id) VALUES ('Piotr', 'Zieliński', 26, 'POLSKA', 4);
INSERT INTO footballer (first_name, last_name, age, country, club_id) VALUES ('Kylian', 'Mbappé', 22, 'FRANCJA', 5);
INSERT INTO footballer (first_name, last_name, age, country, club_id) VALUES ('Neymar', 'da Silva Santos Júnior', 28, 'BRAZYLIA', 5);
INSERT INTO footballer (first_name, last_name, age, country, club_id) VALUES ('Róbert', 'Pich', 32, 'SŁOWACJA', 6);
INSERT INTO footballer (first_name, last_name, age, country, club_id) VALUES ('Filip', 'Marković', 28, 'SERBIA', 6);