package pl.javastart.football.model;

public enum Country {
    AFGANISTAN, ALBANIA, ALGIERIA, ANDORA, ANGOLA, ANTIGUA_I_BARBUDA, ARABIA_SAUDYJSKA, ARGENTYNA, ARMENIA, AUSTRALIA,
    AUSTRIA, AZERBEJDŻAN, BAHAMY, BAHRAJN, BANGLADESZ, BARBADOS, BELGIA, BELIZE, BENIN, BHUTAN, BIAŁORUŚ, BOLIWIA,
    BOŚNIA_I_HERCEGOWINA, BOTSWANA, BRAZYLIA, BRUNEI, BUŁGARIA, BURKINA_FASO, BURUNDI, CHILE, CHINY, CHORWACJA, CYPR,
    CZAD, CZARNOGÓRA, CZECHY, DANIA, DEMOKRATYCZNA_REPUBLIKA_KONGA, DOMINIKA, DOMINIKANA, DŻIBUTI, EGIPT, EKWADOR,
    ERYTREA, ESTONIA, ESWATINI, ETIOPIA, FIDŻI, FILIPINY, FINLANDIA, FRANCJA, GABON, GAMBIA, GHANA, GRECJA, GRENADA,
    GRUZJA, GUJANA, GWATEMALA, GWINEA, GWINEA_BISSAU, GWINEA_RÓWNIKOWA, HAITI, HISZPANIA, HOLANDIA, HONDURAS, INDIE,
    INDONEZJA, IRAK, IRAN, IRLANDIA, ISLANDIA, IZRAEL, JAMAJKA, JAPONIA, JEMEN, JORDANIA, KAMBODŻA, KAMERUN, KANADA,
    KATAR, KAZACHSTAN, KENIA, KIRGISTAN, KIRIBATI, KOLUMBIA, KOMORY, KONGO, KOREA_POŁUDNIOWA, KOREA_PÓŁNOCNA, KOSTARYKA,
    KUBA, KUWEJT, LAOS, LESOTHO, LIBAN, LIBERIA, LIBIA, LIECHTENSTEIN, LITWA, LUKSEMBURG, ŁOTWA, MACEDONIA_PÓŁNOCNA,
    MADAGASKAR, MALAWI, MALEDIWY, MALEZJA, MALI, MALTA, MAROKO, MAURETANIA, MAURITIUS, MEKSYK, MIKRONEZJA, MJANMA,
    MOŁDAWIA, MONAKO, MONGOLIA, MOZAMBIK, NAMIBIA, NAURU, NEPAL, NIEMCY, NIGER, NIGERIA, NIKARAGUA, NORWEGIA,
    NOWA_ZELANDIA, OMAN, PAKISTAN, PALAU, PANAMA, PAPUA_NOWA_GWINEA, PARAGWAJ, PERU, POLSKA, POŁUDNIOWA_AFRYKA,
    PORTUGALIA, REPUBLIKA_ŚRODKOWOAFRYKAŃSKA, REPUBLIKA_ZIELONEGO_PRZYLĄDKA, ROSJA, RUMUNIA, RWANDA, SAINT_KITTS_I_NEVIS,
    SAINT_LUCIA, SAINT_VINCENT_I_GRENADYNY, SALWADOR, SAMOA, SAN_MARINO, SENEGAL, SERBIA, SESZELE, SIERRA_LEONE,
    SINGAPUR, SŁOWACJA, SŁOWENIA, SOMALIA, SRI_LANKA, STANY_ZJEDNOCZONE, SUDAN, SUDAN_POŁUDNIOWY, SURINAM, SYRIA,
    SZWAJCARIA, SZWECJA, TADŻYKISTAN, TAJLANDIA, TANZANIA, TIMOR_WSCHODNI, TOGO, TONGA, TRYNIDAD_I_TOBAGO, TUNEZJA,
    TURCJA, TURKMENISTAN, TUVALU, UGANDA, UKRAINA, URUGWAJ, UZBEKISTAN, VANUATU, WATYKAN, WENEZUELA, WĘGRY,
    WIELKA_BRYTANIA, WIETNAM, WŁOCHY, WYBRZEŻE_KOŚCI_SŁONIOWEJ, WYSPY_MARSHALLA, WYSPY_SALOMONA,
    WYSPY_ŚWIĘTEGO_TOMASZA_I_KSIĄŻĘCA, ZAMBIA, ZIMBABWE, ZJEDNOCZONE_EMIRATY_ARABSKIE
}
